pragma Singleton

import QtQuick
import Quickshell
import Quickshell.Io
import QtCore
import qs.desktop.modules.platform

// Feeds the lock screen its weather.
//
// The lock screen is kscreenlocker's greeter, not this shell: it is a
// different process, with none of Quickshell's types, no D-Bus bindings and
// -- measured, not assumed -- no way to read a file at all. XMLHttpRequest is
// gated behind QML_XHR_ALLOW_FILE_READ, an environment variable the greeter's
// launcher does not set, and Qt.include did not load a local script under any
// form tried. What QML loading *does* do is load QML: so the feed is written
// as a small QML file into the installed theme package, where the lock screen
// picks it up with a plain Loader.
//
// The file is data only -- five property assignments, no logic. state.write
// stages it atomically inside the shell's state root and file.copy publishes
// it into the installed package, both ending in the daemon's tmp+rename, so a
// lock screen never sees a half file. The package probe keeps a desktop that
// is not running this theme from creating an empty package directory as a
// side effect.
QtObject {
    id: service

    // Where kscreenloader looks: the generic data location is what
    // `plasma-lookup` and the greeter both resolve for look-and-feel and shell
    // packages, and it is user-writable by construction.
    readonly property string packageDir:
        StandardPaths.writableLocation(StandardPaths.GenericDataLocation)
        + "/plasma/shells/org.kos.desktop/contents/lockscreen"

    // state.write cannot reach the package directory (it is confined to the
    // quickshell state root), so the feed is staged under stateDir and
    // file.copy publishes it from there. The staging file lives in weather/
    // so it does not collide with any component's config.json.
    readonly property string stagingPath:
        Quickshell.stateDir + "/weather/LockFeed.qml"

    readonly property int refreshMinutes: 5

    function initialize() {
        write()
    }

    function qmlString(value) {
        // JSON strings are valid QML strings, and this escapes everything that
        // needs escaping -- a city name with a quote in it must not end up as
        // QML syntax.
        return JSON.stringify(String(value ?? ""))
    }

    // The lock screen shows what the Dock's weather page shows -- the numbers
    // a glance is actually for -- and no more: a lock screen is not where a
    // forecast gets read.
    function payload() {
        if (!WeatherService.available)
            return ""
        const symbol = WeatherService.conditionSymbol(
            WeatherService.weatherCode, WeatherService.isDay)
        return "// Generated by the desktop shell. Do not edit: it is\n"
            + "// overwritten from WeatherService on a timer.\n"
            + "import QtQuick\n"
            + "QtObject {\n"
            + "    property string weatherSymbol: " + qmlString(symbol) + "\n"
            + "    property string weatherTemperature: "
                + qmlString(WeatherService.temperature) + "\n"
            + "    property string weatherCity: " + qmlString(WeatherService.cityName) + "\n"
            + "    property string weatherCondition: "
                + qmlString(WeatherService.conditionText(WeatherService.weatherCode)) + "\n"
            + "    property string weatherApparent: "
                + qmlString(WeatherService.apparentTemperature) + "\n"
            + "    property string weatherHumidity: " + qmlString(WeatherService.humidity) + "\n"
            + "    property double generatedAt: " + Date.now() + "\n"
            + "}\n"
    }

    function write() {
        const body = payload()
        if (body === "")
            return
        // Re-probe on every write rather than trusting a latched result: a
        // lockscreen installed mid-session starts receiving the feed, and an
        // uninstalled one stops it -- the daemon's file.copy would otherwise
        // mkpath the package directory right back.
        service._pendingBody = body
        _packageProbe.reload()
    }

    // Called once the probe has a fresh answer. The daemon's state ops stay
    // inside the quickshell state root, so the feed is staged there and then
    // copied into the package directory; both steps are daemon-side
    // tmp+rename writes.
    function _publishPending() {
        const body = service._pendingBody
        if (body === "")
            return
        service._pendingBody = ""
        JsonConfigStore.writePath(service.stagingPath, body, function(ok) {
            if (!ok)
                return
            PlatformClient.request("file.copy", {
                source: service.stagingPath,
                destination: service.packageDir + "/LockFeed.qml",
            }, function(response) {
                if (!response?.ok)
                    console.warn("[LockScreenFeed] publish failed: "
                        + (response?.error?.message || "platform unavailable"))
            })
        })
    }

    // WeatherService refreshes about once an hour and pushes on change; the
    // timer is what keeps a stalled push from going stale on the lock screen.
    property Timer _timer: Timer {
        interval: service.refreshMinutes * 60 * 1000
        running: true
        repeat: true
        triggeredOnStart: true
        onTriggered: service.write()
    }

    property Connections _weather: Connections {
        target: WeatherService
        function onCurrentChanged() {
            service.write()
        }
    }

    // Gate on the installed theme like the old `test -f LockScreen.qml` did:
    // on a desktop that never installed this package the probe fails to load
    // and nothing is copied, so no stray plasma package directory appears as
    // a side effect. reload() gives a fresh answer each write, so install and
    // uninstall are both picked up mid-session.
    property FileView _packageProbe: FileView {
        path: service.packageDir + "/LockScreen.qml"
        preload: true
        // A missing package is the expected state on desktops that never
        // installed the lockscreen theme; don't warn every write.
        printErrors: false
        onLoaded: service._publishPending()
        onLoadFailed: function(error) {
            service._pendingBody = ""
        }
    }
    property string _pendingBody: ""
}
